version: '3'
services:
  todotests:
    image: todotest
    depends_on: 
      - todoback
      - todofront
    environment:
      - FRONT_HOST=frontend
    restart:
      - always
  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on: 
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    restart:
      - always
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart:
      - always